"use client";
import Image from"next/image";import Link from"next/link";import{motion}from"framer-motion";import{ArrowDownRight,ArrowUpRight,Heart,Instagram,Menu,Search,ShoppingBag}from"lucide-react";
const Logo=()=> <Link href="/" className="logo">Photo<span>.</span>is<span>.</span>a<span>.</span>Story<small>FINE ART PHOTOGRAPHY</small></Link>;
const works=[
{title:"Where Silence Lives",place:"THE ALPS Â· 2025",src:"/images/stillness-lake.png"},
{title:"Winter Solitude",place:"LOFOTEN Â· 2026",src:"/images/winter-solitude.png"},
{title:"Veins of the Earth",place:"ICELAND Â· 2026",src:"/images/glacial-river.png"},
{title:"Between the Pines",place:"BLACK FOREST Â· 2026",src:"/images/forest-light.png"},
{title:"Atlantic Silence",place:"FAROE ISLANDS Â· 2026",src:"/images/atlantic-silence.png"},
{title:"The Last Light",place:"THE ALPS Â· 2025",src:"/images/stillness-lake.png"}
];
export default function Home(){return <main><header className="nav"><Logo/><nav><a href="#work">Gallery</a><Link href="/prints">Prints</Link><a href="#about">Collections</a><a href="#about">About</a></nav><div><Search/><Heart/><ShoppingBag/><Menu/></div></header>
<section className="hero"><motion.div className="heroImg" initial={{scale:1.1}} animate={{scale:1}} transition={{duration:8}}><Image src="/images/stillness-lake.png" alt="A boat on an alpine lake" fill priority/></motion.div><div className="shade"/><motion.article initial={{opacity:0,y:30}} animate={{opacity:1,y:0}}><p className="eyebrow">FINE ART PHOTOGRAPHY Â· LIMITED EDITIONS</p><h1>Stories written<br/>in <em>light.</em></h1><p>Quiet moments from the world&apos;s wild places,<br/>created to live with you.</p><div className="buttons"><a className="btn gold" href="#work">Explore the gallery <ArrowDownRight/></a><Link className="btn" href="/prints">Shop fine art prints</Link></div></motion.article></section>
<section className="intro" id="about"><p className="eyebrow">ABOUT THE PHOTOGRAPHER</p><h2>Antonis <em>Papadakis.</em></h2><p>I am a landscape photographer and the creator of Photo.is.a.Story. I am drawn to quiet places, changing light and the emotions held within the natural world. My work is about slowing down, observing what often goes unnoticed, and turning fleeting moments into visual stories made to be remembered.</p><p>Through mountains, forests, coastlines and open landscapes, I look for the point where place and feeling become one image.</p><a className="instagramLink" href="https://www.instagram.com/photo.is.a.story/" target="_blank" rel="noreferrer"><Instagram/> Follow @photo.is.a.story <ArrowUpRight/></a></section>
<section className="work" id="work"><header><div><p className="eyebrow">SELECTED WORK</p><h2>Collected <em>stories.</em></h2></div><a>View full gallery <ArrowUpRight/></a></header><div className="grid">{works.map((x,i)=><motion.article key={x.title} initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><div className="photo"><Image src={x.src} alt={x.title} fill sizes="(max-width:700px) 100vw, 33vw"/><span>{String(i+1).padStart(2,"0")}</span></div><h3>{x.title}</h3><p>{x.place}</p></motion.article>)}</div></section>
<section className="interior"><Image src="/images/room-living.png" alt="Fine art in a Scandinavian interior" fill/><div/><article><p className="eyebrow">YOUR WALL Â· YOUR STORY</p><h2>Made to be<br/><em>lived with.</em></h2><p>Museum-grade materials. Hand-finished frames.</p><Link className="btn light" href="/prints">Create your print <ArrowUpRight/></Link></article></section>
<footer><Logo/><p>Photographs for slower living.</p><small>Â© 2026 PHOTO.IS.A.STORY Â· ATHENS / EVERYWHERE</small></footer></main>}