"use client";
import Image from"next/image";import Link from"next/link";import{useMemo,useRef,useState}from"react";import{AnimatePresence,motion}from"framer-motion";import{ArrowLeft,Heart,Menu,Minus,Plus,RotateCcw,ShoppingBag,Sparkles,Upload,X}from"lucide-react";
const sizes=["40 × 60","60 × 90","120 × 80","150 × 100","180 × 120"],sizeCm=[[40,60],[60,90],[120,80],[150,100],[180,120]],mats=["Canvas","Acrylic","Metal","Fine Art Paper"],frames=["Black","White","Oak","Walnut","None"],layouts=[1,2,3,5];
const photos=[
{src:"/images/stillness-lake.png",title:"Where Silence Lives"},
{src:"/images/winter-solitude.png",title:"Winter Solitude"},
{src:"/images/glacial-river.png",title:"Veins of the Earth"},
{src:"/images/forest-light.png",title:"Between the Pines"},
{src:"/images/atlantic-silence.png",title:"Atlantic Silence"},
{src:"/images/stillness-lake.png",title:"The Last Light"},
{src:"/images/afentis-christos.webp",title:"Afentis Christos"},
{src:"/images/dsc-1671.webp",title:"Untold Story"},
{src:"/images/limani.webp",title:"At the Harbour"},
{src:"/images/pagkaki.webp",title:"The Empty Bench"},
{src:"/images/pleasure-beach.webp",title:"Pleasure Beach"},
{src:"/images/theatro.webp",title:"The Theatre"}];
const Opt=({n,title,children}:{n:string,title:string,children:React.ReactNode})=><section className="opt"><header><span>{n}</span><h3>{title}</h3></header>{children}</section>;
export default function Prints(){const[s,setS]=useState(1),[m,setM]=useState(0),[f,setF]=useState(0),[l,setL]=useState(0),[z,setZ]=useState(1),[orientation,setOrientation]=useState<"landscape"|"portrait">("landscape"),[imageRatio,setImageRatio]=useState(1.5),[cropX,setCropX]=useState(50),[cropY,setCropY]=useState(50),[modal,setModal]=useState(""),[selected,setSelected]=useState(photos[0].src),[custom,setCustom]=useState<string|null>(null);const file=useRef<HTMLInputElement>(null),price=useMemo(()=>189+s*60+m*75+(f===4?0:55)+l*18,[s,m,f,l]);const choosePhoto=(src:string)=>{setSelected(src);setCustom(null);setCropX(50);setCropY(50);const preview=new window.Image();preview.onload=()=>setImageRatio(preview.naturalWidth/preview.naturalHeight);preview.src=src};return <main className="studio">
<header className="studioNav"><Link href="/" className="logo">Photo<span>.</span>is<span>.</span>a<span>.</span>Story<small>FINE ART PHOTOGRAPHY</small></Link><Link href="/"><ArrowLeft/> Back to gallery</Link><Menu/></header><div className="studioTitle"><div><p className="eyebrow">PRINT STUDIO</p><h1>Make it <em>yours.</em></h1></div><p>See every detail in your space before it&apos;s made.</p></div>
<div className="config"><aside className="left"><Opt n="01" title="Choose photograph"><div className="thumbs">{photos.map((photo)=><button className={selected===photo.src&&!custom?"active":""} key={photo.title} onClick={()=>choosePhoto(photo.src)} aria-label={`Choose ${photo.title}`}><Image src={photo.src} alt={photo.title} fill/></button>)}</div><button className="upload" onClick={()=>file.current?.click()}><Upload/> Upload your photograph</button><input hidden ref={file} type="file" accept="image/*" onChange={e=>{const x=e.target.files?.[0];if(x){const url=URL.createObjectURL(x);setCustom(url);setSelected(url);setCropX(50);setCropY(50);const preview=new window.Image();preview.onload=()=>setImageRatio(preview.naturalWidth/preview.naturalHeight);preview.src=url}}}/></Opt><Opt n="02" title="Choose layout"><div className="layouts">{layouts.map((x,i)=><button className={l===i?"active":""} onClick={()=>setL(i)} key={x} disabled={x===5||(orientation==="landscape"&&x!==1)} title={x===5?"Coming soon":orientation==="landscape"&&x!==1?"Available in Portrait":undefined}><i>{Array.from({length:x}).map((_,j)=><b key={j}/>)}</i>{["Single","Diptych","Triptych","5 panels"][i]}</button>)}</div></Opt><Opt n="03" title="Choose orientation"><div className="orientations"><button className={orientation==="landscape"?"active":""} onClick={()=>{setOrientation("landscape");setL(0)}}><i className="landscapeShape"/>Landscape</button><button className={orientation==="portrait"?"active":""} onClick={()=>{setOrientation("portrait");setL(1)}}><i className="portraitShape"/>Portrait</button></div></Opt><Opt n="04" title="Adjust crop"><div className="cropControls"><label><span>Horizontal</span><input type="range" min="0" max="100" value={cropX} onChange={e=>setCropX(Number(e.target.value))}/></label><label><span>Vertical</span><input type="range" min="0" max="100" value={cropY} onChange={e=>setCropY(Number(e.target.value))}/></label><button onClick={()=>{setCropX(50);setCropY(50)}}><RotateCcw/> Reset position</button></div></Opt><button className="ai" onClick={()=>setModal("wall")}><Sparkles/> See it on your wall</button></aside>
<section className="preview"><header><span>LIVE PREVIEW · LIVING ROOM</span><div><button onClick={()=>setZ(Math.max(.8,z-.1))}><Minus/></button><b>{Math.round(z*100)}%</b><button onClick={()=>setZ(Math.min(1.2,z+.1))}><Plus/></button><button onClick={()=>setZ(1)}><RotateCcw/></button></div></header><div className="room"><Image src="/images/room-centered.png" alt="Room preview" fill priority/><motion.div className={`art f${f}`} animate={{scale:z,width:`${orientation==="landscape"?Math.max(...sizeCm[s])/3.6:layouts[l]===1?Math.min(...sizeCm[s])/5:Math.min(43,(Math.min(...sizeCm[s])/3.6)*(1+layouts[l]*.28))}%`}} style={{aspectRatio:`${orientation==="landscape"?1.5:layouts[l]===3?imageRatio:layouts[l]*.667} / 1`}}>{Array.from({length:layouts[l]}).map((_,i)=><span key={i} role="img" aria-label={`Artwork panel ${i+1}`}><i style={{width:`${layouts[l]*100}%`,left:`-${i*100}%`}}><Image src={custom||selected} alt="" fill unoptimized={Boolean(custom)} style={{objectFit:"cover",objectPosition:`${cropX}% ${cropY}%`}}/></i></span>)}</motion.div><small>TRUE TO SCALE · {sizes[s]} CM</small></div><div className="rooms">{["Living room","Soft daylight","Gallery wall","Quiet corner"].map((x,i)=><button className={i===0?"active":""} key={x}><span><Image src="/images/room-centered.png" alt="" fill/></span>{x}</button>)}</div></section>
<aside className="right"><Opt n="01" title="Choose size"><div className="sizes">{sizes.map((x,i)=><button className={s===i?"active":""} onClick={()=>setS(i)} key={x}>{x}<small>cm</small></button>)}</div></Opt><Opt n="02" title="Choose material"><div className="materials">{mats.map((x,i)=><button className={m===i?"active":""} onClick={()=>setM(i)} key={x}><i/><span><b>{x}</b><small>{["Tactile, gallery wrapped","Luminous, exceptional depth","Matte, architectural finish","Museum-grade paper"][i]}</small></span></button>)}</div></Opt><Opt n="03" title="Choose frame"><div className="frames">{frames.map((x,i)=><button className={f===i?"active":""} onClick={()=>setF(i)} key={x}><i/>{x}</button>)}</div></Opt><div className="order"><span>Your configuration</span><small>{sizes[s]} cm · {mats[m]} · {layouts[l]} panel · {orientation}</small><div><span>Made to order</span><strong>€{price}.00</strong></div><button className="add" onClick={()=>setModal("cart")}><ShoppingBag/> Add to cart</button><button className="wish"><Heart/> Save to wishlist</button><p>Complimentary insured delivery over €250<br/>Made by hand · Ships in 5–8 business days</p></div></aside></div>
<AnimatePresence>{modal&&<motion.div className="modalWrap" initial={{opacity:0}} animate={{opacity:1}}><div className="modal"><button onClick={()=>setModal("")}><X/></button><Sparkles/><p className="eyebrow">{modal==="cart"?"ADDED TO YOUR COLLECTION":"AI WALL PREVIEW"}</p><h2>{modal==="cart"?"A beautiful choice.":"See it in your space."}</h2><p>{modal==="cart"?`Your ${sizes[s]} cm print is waiting in your cart.`:"Upload a straight-on wall photo. The module is ready for a future AI vision connection."}</p><button className="add">{modal==="cart"?`View cart · €${price}.00`:"Choose room photo"}</button></div></motion.div>}</AnimatePresence></main>}
